[config]
version_check = false

# Changing the syntax
# Expr is for keywords like {{ <keyword> }}
expr_prefix = "{{"
expr_postfix = "}}"

# Block is for stuff like for loops etc.
block_prefix = "<*"
block_postfix = "*>"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.lua"
output_path = "~/.config/hypr/colors.lua"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = "killall -SIGUSR1 kitty 2>/dev/null || true"

[templates.starship]
input_path = "~/.config/matugen/templates/starship.toml"
output_path = "~/.config/starship.toml"

[templates.fastfetch]
input_path = "~/.config/matugen/templates/fastfetch.jsonc"
output_path = "~/.config/fastfetch/config.jsonc"

[templates.btop]
input_path = "~/.config/matugen/templates/btop.theme"
output_path = "~/.config/btop/themes/matugen.theme"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"