---@module 'hl'

-- Runs as the greetd greeter user. Do not point -c at $HOME: greeter cannot
-- read /home/*. hyprlogin loads /etc/hyprlogin/hyprlogin.conf by default.
-- colors.lua is generated by matugen and installed to /etc/hyprlogin/.

local ok, colors = pcall(require, "colors")
if not ok then
    colors = {
        active_border     = "rgba(33ccffee)",
        active_border_alt = "rgba(00ff99ee)",
        inactive_border   = "rgba(595959aa)",
        window_shadow     = 0xee1a1a1a,
        bg_color          = "rgba(111111ff)",
    }
end

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

hl.config({
    general = {
        border_size = 1,
        col = {
            active_border   = { colors = { colors.active_border, colors.active_border_alt }, angle = 45 },
            inactive_border = colors.inactive_border,
        },
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,
        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = colors.window_shadow,
        },
    },

    misc = {
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
        force_default_wallpaper  = 0,
        background_color         = colors.bg_color,
    },

    input = {
        kb_layout = "cz",
    },
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprlogin")
end)
