-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- sample hyprlogin.conf

--

-- rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)

--

-- shortcuts:

-- - ESC on an empty password field returns to username entry

-- - ESC / Ctrl+U / Ctrl+Backspace clear the current field

-- - Tab / Shift+Tab cycle the selected session

--

-- Install this file to /etc/hyprlogin/hyprlogin.conf (greeter cannot read $HOME).

-- If that file does not exist, hyprlogin falls back to the installed example.

--

-- optional greeter defaults:

-- sessions:default_user = your_username

-- sessions:default_session = hyprland.desktop

--

hl.config({
    sessions = {
        default_user = "razj",
        default_session = "hyprland.desktop",
    },
})
-- NOTE: Section 'sessions' may be a plugin or custom section; verify the output

local font = "Monospace"

hl.config({
    general = {
        hide_cursor = false,
        immediate_render = true,
        exit_command = "hyprctl dispatch exit",
        fail_timeout = 4000,
        debug_mode = false,
        debug_log_path = "/tmp/hyprlogin-debug.log",
    },
})

-- uncomment to enable fingerprint authentication

-- auth {

--     fingerprint {

--         enabled = true

--         ready_message = Scan fingerprint to unlock

--         present_message = Scanning...

--         retry_delay = 250 # in milliseconds

--     }

-- }

hl.config({
    animations = {
        enabled = true,
    },
})
hl.curve("linear", {
    type = "bezier",
    points = { { 1, 1 }, { 0, 0 } },
})
hl.animation({ leaf = "fadeIn", enabled = true, speed = 5, bezier = "linear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 5, bezier = "linear" })
hl.animation({ leaf = "inputFieldDots", enabled = true, speed = 2, bezier = "linear" })

hl.config({
    background = {
        path = "/usr/share/hypr/wall2.png",
        blur_passes = 3,
    },
})
-- NOTE: Section 'background' may be a plugin or custom section; verify the output

hl.config({
    input-field = {
        size = { "20%", "5%" },
        outline_thickness = 3,
        inner_color = { "rgba(0", 0, 0, "0.0)" },
        outer_color = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
        check_color = { colors = { "rgba(00ff99ee)", "rgba(ff6633ee)" }, angle = 120 },
        fail_color = { colors = { "rgba(ff6633ee)", "rgba(ff0066ee)" }, angle = 40 },
        font_color = { "rgb(255", 255, "255)" },
        fade_on_empty = false,
        rounding = 15,
        font_family = "Monospace",
        placeholder_text = "Input password...",
        placeholder_text_username = "Input username...",
        fail_text = FAIL,
        -- check_text = Authenticating...
        -- uncomment to use a letter instead of a dot to indicate the typed password
        -- dots_text_format = *
        -- dots_size = 0.4
        dots_spacing = 0.3,
        -- uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
        -- hide_input = true
        position = { 0, -20 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'input-field' may be a plugin or custom section; verify the output

hl.config({
    label = {
        text = TIME,
        font_size = 90,
        font_family = "Monospace",
        position = { -30, 0 },
        halign = "right",
        valign = "top",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

hl.config({
    label = {
        text = "cmd[update:60000] date+ %A, %d %B %Y",
        -- update every 60 seconds
        font_size = 25,
        font_family = "Monospace",
        position = { -30, -150 },
        halign = "right",
        valign = "top",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

hl.config({
    label = {
        text = { LAYOUT[en, "ru]" },
        font_size = 24,
        onclick = "hyprctl switchxkblayout all next",
        position = { 250, -20 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

hl.config({
    label = {
        text = GREETD_SESSION,
        font_size = 16,
        color = { "rgba(200", 200, 200, "1.0)" },
        font_family = "Monospace",
        onclick = "hyprlogin:session_next",
        position = { 30, 30 },
        halign = "left",
        valign = "bottom",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- A greet message that only appears after a username is entered or set via

-- sessions:default_user. See hide_when_empty below.

hl.config({
    label = {
        text = "Login as local_var_GREETD_USER",
        font_size = 16,
        font_family = "Monospace",
        position = { 0, 20 },
        halign = "center",
        valign = "center",
        hide_when_empty = true,
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output
