-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Runs as the greetd greeter user. Do not point -c at $HOME: greeter cannot

-- read /home/*. hyprlogin loads /etc/hyprlogin/hyprlogin.conf by default.


hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 0,
    },
})

hl.config({
    input = {
        kb_layout = "cz",
    },
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprlogin")
end)
