<* if {{ is_dark_mode }} *>
background-color={{ colors.source_color.default.hex | set_lightness: 16.0 | set_saturation: 42.0 }}85
text-color={{ colors.on_surface.default.hex }}
border-color={{ colors.primary.default.hex | set_saturation: 40.0 | set_lightness: 88.0 }}99
progress-color=source {{ colors.primary.default.hex | set_saturation: 78.0 | set_lightness: 62.0 }}cc
<* else *>
background-color={{ colors.source_color.default.hex | set_saturation: 28.0 | set_lightness: 93.0 }}c7
text-color={{ colors.on_surface.default.hex | set_lightness: 12.0 }}
border-color={{ colors.primary.default.hex | set_saturation: 40.0 | set_lightness: 100.0 }}cc
progress-color=source {{ colors.primary.default.hex | set_saturation: 82.0 | set_lightness: 48.0 }}d4
<* endif *>

font=Source Sans 3 Medium 13
width=400
height=140
padding=14,16
margin=10
outer-margin=16
border-size=1
border-radius=16
icons=1
max-icon-size=48
icon-location=left
icon-border-radius=12
markup=1
format=<b>%s</b>\n<span alpha="85%%">%b</span>
text-alignment=left
anchor=top-right
layer=overlay
default-timeout=10000
max-history=10

[urgency=low]
<* if {{ is_dark_mode }} *>
background-color={{ colors.source_color.default.hex | set_lightness: 16.0 | set_saturation: 36.0 }}66
border-color={{ colors.primary.default.hex | set_saturation: 28.0 | set_lightness: 88.0 }}66
<* else *>
background-color={{ colors.source_color.default.hex | set_saturation: 22.0 | set_lightness: 94.0 }}8c
border-color={{ colors.primary.default.hex | set_saturation: 24.0 | set_lightness: 100.0 }}99
<* endif *>

[urgency=critical]
<* if {{ is_dark_mode }} *>
background-color={{ colors.primary.default.hex | set_hue: 8.0 | set_saturation: 48.0 | set_lightness: 22.0 }}a6
text-color={{ colors.on_surface.default.hex }}
border-color={{ colors.primary.default.hex | set_hue: 8.0 | set_saturation: 55.0 | set_lightness: 78.0 }}ee
progress-color=source {{ colors.primary.default.hex | set_hue: 8.0 | set_saturation: 82.0 | set_lightness: 58.0 }}d4
<* else *>
background-color={{ colors.primary.default.hex | set_hue: 8.0 | set_saturation: 36.0 | set_lightness: 90.0 }}d4
text-color={{ colors.on_surface.default.hex | set_lightness: 12.0 }}
border-color={{ colors.primary.default.hex | set_hue: 8.0 | set_saturation: 78.0 | set_lightness: 46.0 }}ee
progress-color=source {{ colors.primary.default.hex | set_hue: 8.0 | set_saturation: 84.0 | set_lightness: 48.0 }}d4
<* endif *>
